stages:
  data_cleaning:
    cmd: python src/data/data_cleaning.py
    deps:
      - data/raw/kidney_disease.csv
      - data/raw/indian_liver_patient.csv
      - data/raw/diabetes.csv
      - data/raw/cancer.csv
      - data/raw/heart.csv  # Add this as a dependency
      - src/data/data_cleaning.py
    outs:
      - data/processed/kidney_cleanned.csv
      - data/processed/processed_liver_data.csv
      - data/processed/diabetes_cleanned.csv
      - data/processed/cancer_cleanned.csv
      - data/processed/processed_heart_disease.csv  # Add this output file



#   cancer_cleaning:
#     cmd: python src/data/cancer_cleaning.py
#     deps:
#       - data/raw/cancer.csv
#       - src/data/cancer_cleaning.py
#     outs:
#       - data/processed/cancer_cleanned.csv
#   liver_cleaning:
#     cmd: python src/data/liver_cleaning.py
#     deps:
#       - data/raw/indian_liver_patient.csv
#       - src/data/liver_cleaning.py
#     outs:
#       - data/processed/processed_liver_data.csv
#   kidney_cleaning:
#     cmd: python src/data/kidney_cleaning.py
#     deps:
#       - data/raw/kidney_disease.csv
#       - src/data/kidney_cleaning.py
#     outs:
#       - data/processed/processed_kidney_disease.csv
   
#   heart_cleaning:
#     cmd: python src/data/heart_cleaning.py
#     deps:
#       - data/raw/heart.csv
#       - src/data/heart_cleaning.py
#     outs:
#       - data/processed/processed_heart_disease.csv 

#   diabetes_cleaning:
#     cmd: python src/data/diabetes_cleaning.py
#     deps:
#       - data/raw/diabetes.csv
#       - src/data/diabetes_cleaning.py
#     outs:
#       - data/processed/diabetes_cleanned.csv 
#   # data_preparation:
#   #   cmd: python src/data/data_preparation.py
#   #   params:
#   #   - Data_Preparation.test_size
#   #   - Data_Preparation.random_state
#   #   deps:
#   #   - data/cleaned/swiggy_cleaned.csv
#   #   - src/data/data_preparation.py
#   #   outs:
#   #   - data/interim/train.csv
#   #   - data/interim/test.csv

#   # data_preprocessing:
#   #   cmd: python src/features/data_preprocessing.py
#   #   deps:
#   #   - data/interim/train.csv
#   #   - data/interim/test.csv
#   #   - src/features/data_preprocessing.py
#   #   outs:
#   #   - data/processed/train_trans.csv
#   #   - data/processed/test_trans.csv
#   #   - models/preprocessor.joblib

#   # train:
#   #   cmd: python src/models/train.py
#   #   deps:
#   #   - src/models/train.py
#   #   - data/processed/train_trans.csv
#   #   params:
#   #   - Train.Random_Forest
#   #   - Train.LightGBM
#   #   outs:
#   #   - models/model.joblib
#   #   - models/power_transformer.joblib
#   #   - models/stacking_regressor.joblib

#   # evaluation:
#   #   cmd: python src/models/evaluation.py
#   #   deps:
#   #   - src/models/evaluation.py
#   #   - data/processed/train_trans.csv
#   #   - data/processed/test_trans.csv
#   #   - models/model.joblib
#   #   outs:
#   #   - run_information.json

#   # register_model:
#   #   cmd: python src/models/register_model.py
#   #   deps:
#   #   - src/models/register_model.py
#   #   - run_information.json